export let cookiesLegalContent = {
    content: "<h2 style='text-align: center;'><strong>Cookies:  CineKomuna</strong></h2> "+
    "<p style='text-align: center;'>&nbsp;</p>"+
    "<p>&nbsp;</p>"+
    "<p><strong>&iquest;Qu&eacute; son las Cookies?</strong><br />Una &ldquo;Cookie&rdquo; es un peque&ntilde;o archivo de datos que es enviado a tu dispositivo cuando accedes a la plataforma y sitio web de Cinekomuna. Este archivo de datos se almacena en los servidores de Cinekomuna y de terceros as&iacute; como en los dispositivos y navegadores de los USUARIOS y recaba cierta informaci&oacute;n sobre el uso del servicio brindado por Cinekomuna a trav&eacute;s de su plataforma/ Sitio web.</p>"+
    "<p>Son &uacute;nicos para cada USUARIO o su navegador web y pueden contener informaci&oacute;n de identificaci&oacute;n personal, as&iacute; como informaci&oacute;n t&eacute;cnica (por ejemplo, el fabricante y modelo de su dispositivo, resoluci&oacute;n de pantalla, proveedor de servicios de Internet, navegador y datos de ubicaci&oacute;n geogr&aacute;fica). Las cookies basadas en sesi&oacute;n duran solo mientras su navegador est&aacute; abierto y se eliminan autom&aacute;ticamente cuando cierra el navegador. Las cookies persistentes duran hasta que usted o su navegador las eliminan, o hasta que caducan.</p>"+
    "<p><strong>Uso de Cookies</strong><br />Cinekomuna utiliza cookies propias y de terceros cuando un USUARIO navega por el SITIO WEB. Gracias a las cookies, resulta posible que los servidores de Cinekomuna o de terceros reconozca el navegador del equipo utilizado por el USUARIO con la finalidad de que la navegaci&oacute;n sea m&aacute;s sencilla dentro del ecosistema Cinekomuna, permitiendo, por ejemplo, el acceso a los Usuarios que se hayan registrado previamente, acceder a las &aacute;reas, servicios, promociones reservados exclusivamente a ellos sin tener que registrarse en cada visita. Se utilizan tambi&eacute;n para medir la audiencia y par&aacute;metros del tr&aacute;fico, controlar el progreso y n&uacute;mero de entradas. Asimismo Cinekomuna podr&aacute; utilizar los &ldquo;cookies&rdquo; para velar por la seguridad de sus usuarios, as&iacute; como para poder mejorar la calidad y experiencia de los servicios ofrecidos en el SITIO WEB,</p>"+
    "<p>De igual manera, los servidores web de Cinekomuna detectan de manera autom&aacute;tica la direcci&oacute;n IP y el nombre de dominio utilizados por el usuario. Toda esta informaci&oacute;n es registrada en un fichero de actividad y base de datos del servidor que permite el posterior procesamiento de los datos con el fin de obtener mediciones estad&iacute;sticas que permitan conocer el n&uacute;mero de impresiones de p&aacute;ginas, el n&uacute;mero de visitas realizadas a los servicios web, etc.</p>"+
    "<p><strong>An&aacute;lisis</strong><br />Las Cookies nos ayudan a mejorar y a hacer un an&aacute;lisis detallado de las funciones y contenido del sitio web, esto nos permite mejorar la experiencia de interacci&oacute;n con las herramientas del sitio. Algunos de estos servicios son prove&iacute;dos por Google Analytics?.</p>"+
    "<p><strong>Seguridad</strong><br />Cinekomuna utiliza las Cookies para evitar que terceros puedan acceder a tu cuenta y nos alertan, tanto a ti como a nosotros, en caso de que esto ocurra. Adem&aacute;s, nos brindan la capacidad de desactivar cualquier sesi&oacute;n activa en caso de que haya una violaci&oacute;n de seguridad y necesites cerrar las cuentas que tengas abiertas en otros dispositivos.</p>"+
    "<p><strong>Localizaci&oacute;n</strong><br />Algunas cookies nos ayudan a ofrecer experiencias y/o servicios en relaci&oacute;n al lugar en donde te encuentras ubicado.</p>"+
    "<p><strong>Mercadotecnia</strong><br />Las Cookies nos ayudan a publicar anuncios personalizados en redes sociales basados en tu actividad, comportamiento y preferencias mostradas dentro del SITIO WEB.</p>"+
    "<p>En algunos casos, nuestros socios usan Cookies para proporcionarnos informaci&oacute;n sobre la interacci&oacute;n de los USUARIOS con sus servicios.</p>"+
    "<p>Estas Cookies de terceros se rigen por las respectivas pol&iacute;ticas del servicio que tengan dichos socios y/o afiliados.</p>"+
    "<p><strong>Redes sociales</strong><br />Las Cookies juegan un rol importante en la relaci&oacute;n que se da entre Cinekomuna y las redes sociales. Esta interacci&oacute;n permite que el SITIO WEB le brinde a sus USUARIOS ciertas funciones que se encuentran directamente relacionadas con la red social con la que comparte las Cookies.</p>"+
    "<p>Por ejemplo, habilitar las &ldquo;cookies&rdquo; permite iniciar sesi&oacute;n en el SITIO WEB con la cuenta de alguna red social. En la mayor&iacute;a de los casos, estas funciones son controladas por cada red social en particular y cada una se rige por sus propias pol&iacute;ticas de privacidad y por las preferencias establecidas en la misma.</p>"+
    "<p><strong>Tipos de Cookies</strong><br />Cinekomuna utiliza los tipos cookies que se detallan a continuaci&oacute;n:</p>"+
    "<ul>"+
    "<li>Cookies estrictamente necesarias para la prestaci&oacute;n de determinados servicios solicitados expresamente por el usuario: si se desactivan estas cookies, no podr&aacute; recibir correctamente nuestros contenidos y servicios. (Ejemplos de cookies estrictamente necesarias: sesi&oacute;n, registro, datos para distinguir los servicios gratuitos de los servicios de pago, etc)</li>"+
    "<li>Cookies anal&iacute;ticas (para el seguimiento y an&aacute;lisis estad&iacute;stico del comportamiento del conjunto de los usuarios), publicitarias (para la gesti&oacute;n de los espacios publicitarios en base a criterios como la frecuencia en la que se muestran los anuncios) y comportamentales (para la gesti&oacute;n de los espacios publicitarios seg&uacute;n el perfil espec&iacute;fico del usuario): si se desactivan estas cookies, el sitio web podr&aacute; seguir funcionando sin perjuicio de que la informaci&oacute;n captada por estas cookies sobre el uso de nuestra web y sobre el &eacute;xito de los anuncios mostrados en ella permite mejorar nuestros servicios y obtener ingresos que nos permiten ofrecerle de forma gratuita muchos contenidos.</li>"+
    "</ul>"+
    "<p><strong>Revocaci&oacute;n y eliminaci&oacute;n de Cookies</strong><br />Cinekomuna informa que el USUARIO tiene la posibilidad de configurar su navegador para ser avisado en pantalla de la recepci&oacute;n de cookies y para impedir su instalaci&oacute;n en su disco duro. Asimismo existe la posibilidad de que la configuraci&oacute;n de tu navegador te permite controlar las Cookies y en consecuencia rechazar o aprobar las mismas.</p>"+
    "<p><br />Por favor, consulte las instrucciones y manuales de su navegador para ampliar esta informaci&oacute;n. Es necesario que el USUARIO sepa que el bloqueo o la eliminaci&oacute;n de las Cookies podr&iacute;a impedirle utilizar algunas de las funciones disponibles dentro del SITIO WEB.<br /> <br />Dicho esto, el USUARIO reconoce y acepta de forma consciente e informada que dichos servicios sean utilizados en la forma y t&eacute;rminos descritos en la presente secci&oacute;n.<br /> <br /> <strong>&iquest;Preguntas y/o contacto?</strong><br /> <br />Si tienes cualquier pregunta y/o sugerencia, por favor no dudes en escribirnos a ______</p>"+
    "<p><strong>Fecha &uacute;ltima de actualizaci&oacute;n: 1 de noviembre de 2020.</strong></p>"+
    "<p>&nbsp;</p>"
}