export let privacyLegalContent = {
    content: "<h2 style='text-align: center;'><strong>Aviso de Privacidad de CineKomuna</strong></h2> "+
    "<p style='text-align: center;'>&nbsp;</p>"+
    "<p>&nbsp;</p>"+
    "<p>Cinekomuna S.A.P.I de C.V. es responsable del uso y protecci&oacute;n de los datos personales de sus USUARIOS, en este sentido y atendiendo las obligaciones legales establecidas en la Ley Federal de Protecci&oacute;n de Datos Personales en Posesi&oacute;n de los Particulares, a trav&eacute;s de este instrumento se informa a los titulares de los datos, la informaci&oacute;n que de ellos se recaba y los fines que se le dar&aacute;n a dicha informaci&oacute;n.</p>"+
    "<p>Junto con los T&eacute;rminos y condiciones, esta Pol&iacute;tica de privacidad establece nuestros acuerdos con usted como USUARIO de nuestro SITIO WEB. El siguiente aviso de privacidad ha sido creado para ayudarlo a comprender los datos personales que podemos recopilar, c&oacute;mo pretendemos procesar y almacenar esos datos de manera segura y los derechos que tiene en relaci&oacute;n con sus datos personales.</p>"+
    "<p>Adem&aacute;s de lo anterior, informamos a usted que Cinekomuna S.A.P.I de C.V. tiene su domicilio ubicado en: Ruise&ntilde;or 26, Colonia el Rosedal, Alcald&iacute;a Coyoac&aacute;n, CP 04330, CDMX</p>"+
    "<p><strong>Datos</strong><br />La informaci&oacute;n requerida al USUARIO var&iacute;a seg&uacute;n el tipo de perfil o perfiles (Crew, cast, proyectos, empresa) que est&eacute; creando. Se requiere cierta informaci&oacute;n y otra es opcional; esto se aclara en el momento en que se solicite la informaci&oacute;n para dar de alta un perfil nuevo.</p>"+
    "<p>Para llevar a cabo las finalidades descritas as&iacute; como la correcta gesti&oacute;n de los servicios ofrecidos a trav&eacute;s de nuestra SITIO WEB en el presente aviso de privacidad, utilizaremos los siguientes datos personales del USUARIO:</p>"+
    "<ul>"+
    "<li>Datos identificativos y de contacto del USUARIO (datos como nombre, apellidos, edad, email, etc)</li>"+
    "<li>Imagen y voz del USUARIO (incluidos en las fotos, v&iacute;deos y audios incluidos en la plataforma)</li>"+
    "<li>Curr&iacute;culum y biograf&iacute;a del USUARIO en el caso de que lo proporcione (formaci&oacute;n, experiencia, trayectoria profesional y/o art&iacute;stica, etc)</li>"+
    "<li>En el caso de USUARIOS que tengan perfil de &ldquo;Cast&rdquo;, caracter&iacute;sticas personales y f&iacute;sicas (todos aquellos datos que el USUARIO facilite sobre sus habilidades, personalidad y rasgos f&iacute;sicos)</li>"+
    "<li>Datos que publique el USUARIO en sus redes sociales cuando est&eacute;n conectadas a nuestros servicios</li>"+
    "<li>Si opta por una suscripci&oacute;n a una membres&iacute;a premium: informaci&oacute;n de pago e informaci&oacute;n de transacci&oacute;n de que pudieran ser requeridos por los administradores del SITIO WEB (nota: El SITIO WEB no almacena los datos de la tarjeta de cr&eacute;dito as&iacute; como cualquier informacion financiera del USUARIO, esta informaci&oacute;n es administrada y almacenada por nuestro gestor de pagos ______)</li>"+
    "<li>Informaci&oacute;n sobre cualquier proyecto audiovisual con el cual el USUARIO pudiera tener alguna relaci&oacute;n.</li>"+
    "</ul>"+
    "<p>De igual manera se podr&iacute;an recolectar los siguientes datos del Usuario:</p>"+
    "<ul>"+
    "<li>Informaci&oacute;n t&eacute;cnica, incluida la direcci&oacute;n de protocolo de Internet (IP) utilizada para conectar su computadora a Internet, su informaci&oacute;n de inicio de sesi&oacute;n, tipo y versi&oacute;n de navegador, configuraci&oacute;n de zona horaria, tipos y versiones de complementos del navegador, sistema operativo y plataforma;</li>"+
    "<li>Informaci&oacute;n sobre su visita, incluido el flujo de clics completo de los localizadores uniformes de recursos (URL) hac&iacute;a, a trav&eacute;s y desde el sitio web (incluida la fecha y la hora); p&aacute;ginas que vio o busc&oacute;; tiempos de respuesta de la p&aacute;gina, errores de descarga, duraci&oacute;n de las visitas a determinadas p&aacute;ginas, informaci&oacute;n de interacci&oacute;n de la p&aacute;gina (como desplazamiento, clics y desplazamientos del mouse), m&eacute;todos utilizados para navegar fuera de la p&aacute;gina y cualquier n&uacute;mero de tel&eacute;fono utilizado para llamar a nuestro n&uacute;mero de servicio al cliente.</li>"+
    "<li>El SITIO WEB trabaja en estrecha colaboraci&oacute;n con terceros adicionales (incluidos, por ejemplo, socios comerciales, subcontratistas de servicios t&eacute;cnicos, de pago y entrega, redes publicitarias, proveedores de an&aacute;lisis, proveedores de informaci&oacute;n de b&uacute;squeda, agencias de referencia crediticia) y podemos recibir informaci&oacute;n sobre usted de ellos.</li>"+
    "</ul>"+
    "<p>Al proporcionar sus datos al SITIO WEB, el USUARIO garantiza que son verdaderos, exactos, completos y actualizados. En aquellos casos en que el USUARIO proporcione datos personales de terceros, el USUARIO garantiza y manifiesta que dispone del consentimiento expreso del titular de los mismos para dicha cesi&oacute;n. El USUARIO se asume el &uacute;nico responsable de cualquier da&ntilde;o o perjuicio, directo o indirecto, que pudiera ocasionarse como consecuencia del incumplimiento de tales obligaciones.</p>"+
    "<p>Al hacer un registro, llenar y publicar un perfil y otro contenido, el USUARIO reconoce y acepta que este ser&aacute; visible para otros USUARIOS y/o el p&uacute;blico general de acuerdo con los servicios que les brindamos.</p>"+
    "<p>El USUARIO podr&aacute; brindar sus datos e informaci&oacute;n al SITIO WEB al completar formularios en el SITIO WEB o al comunicarse con los administrados del SITIO WEB v&iacute;a tel&eacute;fono, correo electr&oacute;nico o de otro modo. Esto incluye la informaci&oacute;n que proporciona cuando se registra para usar el sitio web, se suscribe a nuestros servicios, participa en foros de discusi&oacute;n u otras funciones de redes sociales en el sitio web y cuando informa un problema con el sitio web.</p>"+
    "<p>El SITIO WEB puede, de vez en cuando, contener enlaces hacia y desde los sitios web de nuestras redes de socios, anunciantes y afiliados. El USUARIO reconoce y acepta que al seleccionar y acceder a un enlace de un tercero, pueda tener pol&iacute;ticas de privacidad propias y distintas a las del SITIO WEB y que Cinekomuna no acepta ninguna responsabilidad por estas pol&iacute;ticas.</p>"+
    "<p><strong>Finalidad del tratamiento de los datos personales</strong><br />Los datos personales que proporcione el USUARIO ser&aacute;n utilizados para las siguientes finalidades, las cuales son necesarias para concretar la relaci&oacute;n del SITIO WEB con el USUARIO, as&iacute; como para atender los servicios y/o pedidos que solicite:</p>"+
    "<ul>"+
    "<li>Para brindarle acceso a los servicios del SITIO WEB y permitir que otros usuarios vean e interact&uacute;en con el perfil del USUARIO y otra informaci&oacute;n p&uacute;blicamente disponible publicada por dicho USUARIO en el SITIO WEB.</li>"+
    "<li>Para administrar el sitio web y para operaciones internas, incluida la resoluci&oacute;n de problemas, an&aacute;lisis de datos, pruebas, investigaci&oacute;n, estad&iacute;sticas y encuestas.</li>"+
    "<li>Para mantener la relaci&oacute;n contractual del USUARIO con Cinekomuna</li>"+
    "<li>Para la gesti&oacute;n, administraci&oacute;n, prestaci&oacute;n, ampliaci&oacute;n y mejora de los servicios a los que decida suscribirse el USUARIO, darse de alta o utilizar, y para la adecuaci&oacute;n de dichos servicios a las preferencias y gustos de dicho USUARIO.</li>"+
    "<li>Para mostrar, o permitir a terceros mostrar, al USUARIO publicidad relevante y de posible inter&eacute;s sobre bienes y servicios, seg&uacute;n sus intereses y preferencias.</li>"+
    "<li>Para la promoci&oacute;n de nuestros productos y servicios.</li>"+
    "<li>Para atender solicitudes de consulta, informaci&oacute;n, quejas y reclamaciones.</li>"+
    "<li>Para el cumplimiento de las disposiciones legales aplicables y de las obligaciones contra&iacute;das con nuestros USUARIOS.</li>"+
    "</ul>"+
    "<p><strong>Transferencia de datos personales</strong><br /> A efecto de estar en posibilidad de dar cumplimiento a las finalidades previstas en este aviso de privacidad, cuando a juicio de Cinekomuna sea necesario, se podr&aacute; efectuar la transferencia de ciertos datos personales de nuestros USUARIOS a favor de terceros, comprometi&eacute;ndose en todo caso Cinekomuna a velar por el cumplimiento de los principios de protecci&oacute;n de datos personales establecidos en la Ley y a tomar las medidas necesarias y suficientes para garantizar que tanto la Ley como este aviso de privacidad sean respetados en todo momento por &eacute;l o los terceros a los que Cinekomuna transfiera los datos personales.<br /> <br />En este sentido, Cinekomuna podr&aacute; realizar la transferencia de sus datos personales, entre otros, a sus empresas subsidiarias y afiliadas, socios comerciales, proveedores y subcontratistas para la ejecuci&oacute;n de cualquier contrato que se celebre con ellos o con el USUARIO, prestadores de servicios necesarios para la correcta operaci&oacute;n del SITIO WEB, proveedores de servicios generales y asesores profesionales, autoridades, organismos gubernamentales y autoridades policiales, anunciantes y redes publicitarias que requieren la informaci&oacute;n para seleccionar y ofrecer anuncios relevantes para el USUARIO (Cinekomuna no divulga informaci&oacute;n sobre personas identificables a anunciantes, pero proporciona informaci&oacute;n agregada sobre nuestros USUARIOS. Cinekomuna tambi&eacute;n podr&aacute; utilizar dicha informaci&oacute;n agregada para ayudar a los anunciantes a llegar al tipo de p&uacute;blico al que quieren dirigirse, proveedores de servicios que requieren la informaci&oacute;n de los USUARIOS para brindar sus servicios), proveedores de an&aacute;lisis y motores de b&uacute;squeda que ayuden a mejorar y optimizar el sitio web.</p>"+
    "<p>Salvo que el USUARIO manifieste su oposici&oacute;n, se entender&aacute; que otorga su consentimiento a Cinekomuna para transferir a terceros sus datos personales, siempre que ello sea necesario para el cumplimiento de las finalidades establecidas en el presente aviso de privacidad. Lo anterior en el entendido que el tercero receptor asumir&aacute; las mismas responsabilidades y/u obligaciones de Cinekomuna derivadas del presente aviso de privacidad, debiendo respetar el mismo en todo momento.</p>"+
    "<p>No obstante lo anterior, Cinekomuna podr&aacute; llevar a cabo la transferencia de los datos personales del USUARIO sin consentimiento del titular en los siguientes casos: </p>"+
    "<ul>"+
    "<li>Cuando la transferencia est&eacute; prevista en una ley o tratado en los que los Estados Unidos Mexicanos sean parte.</li>"+
    "<li>Cuando la transferencia sea necesaria o legalmente exigida para la salvaguarda de un inter&eacute;s p&uacute;blico, o para la procuraci&oacute;n o administraci&oacute;n de justicia.</li>"+
    "<li>Cuando la transferencia sea precisa para el reconocimiento, ejercicio o defensa de un derecho en un proceso judicial.</li>"+
    "<li>Cuando la transferencia sea precisa para el mantenimiento o cumplimiento de una relaci&oacute;n jur&iacute;dica entre el responsable y el titular.</li>"+
    "</ul>"+
    "<p><strong>Almacenamiento y seguridad de sus datos personales</strong><br />Los datos personales del USUARIO se almacenan en registros electr&oacute;nicos y f&iacute;sicos mantenidos por Cinekomuna y/o nuestros proveedores de servicios. Si bien nuestras oficinas est&aacute;n ubicadas en territorio nacional, nuestros proveedores de servicios pueden tener servidores ubicados fuera del pa&iacute;s.</p>"+
    "<p>El SITIO WEB conservar&aacute; la informaci&oacute;n y datos del USUARIO durante el tiempo que sea necesario para cumplir con el servicio que ofrece o para cumplir con las solicitudes de los organismos encargados de hacer cumplir la ley o los reguladores.</p>"+
    "<p>El USUARIO reconoce y acepta, dada la naturaleza de Internet, los datos transmitidos a trav&eacute;s de nuestros Sitios o por correo electr&oacute;nico no son completamente seguros contra el acceso no autorizado o el uso indebido.</p>"+
    "<p><strong>Consultas y derechos del usuario</strong><br />De conformidad con lo dispuesto en la Ley, el USUARIO tendr&aacute; el derecho, en todo momento, de acceder a sus datos personales en poder de Cinekomuna; rectificarlos en caso de que &eacute;stos sean inexactos o est&eacute;n incompletos; instruirnos a cancelarlos cuando considere que son excesivos o innecesarios para las finalidades que justificaron su obtenci&oacute;n o haya finalizado la relaci&oacute;n contractual con Cinekomuna; as&iacute; como a oponerse por causa leg&iacute;tima al tratamiento de sus datos personales.</p>"+
    "<p>El USUARIO tiene en todo momento el derecho a conocer qu&eacute; datos personales almacena Cinekomuna, para que son utilizados y las condiciones del uso que se les da.</p>"+
    "<p>En caso de que el USUARIO requiera hacer alguna consulta simple o exhaustiva para ejercer sus derechos, Cinekomuna pone a su disposici&oacute;n el siguiente correo _______________</p>"+
    "<p><strong>Plazo de conservaci&oacute;n de los datos personales</strong><br />Cinekomuna tratar&aacute; y almacenar&aacute; los datos de un USUARIO durante la vigencia de relaci&oacute;n entre el USUARIO y Cinekomuna y hasta extinguir las obligaciones y responsabilidades nacidas del tratamiento de datos del USUARIO en cuesti&oacute;n.</p>"+
    "<p><strong>Modificaciones al Aviso de Privacidad</strong><br />Cinekomuna se reserva el derecho de efectuar, en cualquier momento, modificaciones o actualizaciones a este aviso de privacidad, ya sea como consecuencia de reformas legislativas, pol&iacute;ticas internas, nuevos requerimientos para la prestaci&oacute;n u ofrecimiento de nuestros servicios y/o productos, pr&aacute;cticas del mercado u otros.</p>"+
    "<p>Cualquier cambio que Cinekomuna llegu&eacute; a hacer su pol&iacute;tica de privacidad en el futuro se publicar&aacute; en esta p&aacute;gina y, cuando corresponda, se le notificar&aacute; por correo electr&oacute;nico al USUARIO. Se recomienda al USUARIO consultar con frecuencia esta p&aacute;gina para ver actualizaciones o cambios en nuestra pol&iacute;tica de privacidad.</p>"+
    "<p>Agradecemos que, al unirse a nuestra plataforma, nos haya confiado sus datos. Con esto en mente, nos comprometemos a respetar su privacidad y ser abiertos sobre lo que recopilamos y c&oacute;mo lo usamos. Haremos todo lo posible para garantizar que sus datos se mantengan seguros.</p>"+
    "<p><strong>Fecha &uacute;ltima de actualizaci&oacute;n: 1 de noviembre de 2020.</strong></p>"+
    "<p>&nbsp;</p>"
}