export let termsLegalContent = {
    content: "<h2 style='text-align: center;'><strong>Uso de la Plataforma CineKomuna</strong></h2> "+
"<p style='text-align: center;'>&nbsp;</p>"+
"<p>&nbsp;</p>"+
"<p><br />Este contrato describe los t&eacute;rminos y condiciones generales (en adelante &uacute;nicamente 'T&Eacute;RMINOS Y CONDICIONES') aplicables al uso de los contenidos, productos y servicios ofrecidos a trav&eacute;s del sitio <strong>cinekomuna.com</strong> (en adelante, 'SITIO WEB'), del cual es titular Cinekomuna S.A.P.I de C.V. (en adelante, 'TITULAR'). Cualquier persona que desee acceder o hacer uso del sitio o los servicios que en &eacute;l se ofrecen, podr&aacute; hacerlo sujet&aacute;ndose a los presentes T&Eacute;RMINOS Y CONDICIONES, as&iacute; como a pol&iacute;ticas y principios incorporados al presente documento. En todo caso, cualquier persona que no acepte los presentes t&eacute;rminos y condiciones, deber&aacute; abstenerse de utilizar el SITIO WEB y/o adquirir los productos y servicios que en su caso sean ofrecidos.</p>"+
"<p><br /><strong>I. DEL OBJETO.</strong><br />El objeto de los presentes T&Eacute;RMINOS Y CONDICIONES es regular el acceso y la utilizaci&oacute;n del SITIO WEB, entendiendo por este cualquier tipo de contenido, producto o servicio que se encuentre a disposici&oacute;n del p&uacute;blico en general dentro del dominio: cinekomuna.com.</p>"+
"<p>El TITULAR se reserva la facultad de modificar en cualquier momento y sin previo aviso, la presentaci&oacute;n, los contenidos, Ia funcionalidad, los productos, los servicios, y Ia configuraci&oacute;n que pudiera estar contenida en el SITIO WEB; en este sentido, el USUARIO reconoce y acepta que CineKomuna en cualquier momento podr&aacute; interrumpir, desactivar o cancelar cualquiera de los elementos que conforman el SITIO WEB o el acceso a los mismos.</p>"+
"<p>El acceso a parte de los contenidos y servicios del SITIO WEB podr&aacute; realizarse previa suscripci&oacute;n o registro previo del USUARIO.</p>"+
"<p>El registro, acceso e interacci&oacute;n como USUARIO dentro del SITIO WEB est&aacute; dirigido exclusivamente a personas que cuenten con la mayor&iacute;a de edad (mayores de 18 a&ntilde;os);</p>"+
"<ul>"+
"<li>Por seguridad de nuestros USUARIOS, el SITIO WEB no permite que un menor de edad pueda crear un perfil por cuenta propia. Dicho esto, dada la naturaleza de la industria audiovisual, pueden haber excepciones y darse el caso donde se pueda hacer un registro y creaci&oacute;n de un perfil de &ldquo;Cast&rdquo; de un menor de edad en cuyo caso solamente el tutor legal/ madre/ o padre del mismo podr&aacute;n crear el perfil y actuar en representaci&oacute;n legal del menor.</li>"+
"</ul>"+
"<p>En este sentido, Cinekomuna declina cualquier responsabilidad por el incumplimiento de este requisito. El USUARIO haciendo el registro del perfil manifiesta ser mayor de edad y disponer de la capacidad jur&iacute;dica necesaria para sujetarse a los presentes T&Eacute;RMINOS Y CONDICIONES.</p>"+
"<p>El SITIO WEB est&aacute; dirigido principalmente a USUARIOS residentes en la Rep&uacute;blica Mexicana, por lo cual, CineKomuna no asegura que el SITIO WEB cumpla total o parcialmente con la legislaci&oacute;n de otros pa&iacute;ses, de forma que, si el USUARIO reside o tiene su domicilio establecido en otro pals y decide acceder o utilizar el SITIO WEB lo har&aacute; bajo su propia responsabilidad y deber&aacute; asegurarse de que tal acceso y navegaci&oacute;n cumple con la legislaci&oacute;n local que le es aplicable, no asumiendo CineKomuna ninguna responsabilidad que se pueda derivar de dicho acto.</p>"+
"<p>Se hace del conocimiento del USUARIO que el TITULAR podr&aacute; administrar o gestionar el SITIO WEB de manera directa o a trav&eacute;s de un tercero, lo cual no modifica en ning&uacute;n sentido lo establecido en los presentes T&Eacute;RMINOS Y CONDICIONES.</p>"+
"<p>Adem&aacute;s del costo de la conexi&oacute;n a internet en virtud de los servicios que el USUARIO tenga contratados con alg&uacute;n proveedor de telecomunicaciones, parte de los contenidos o servicios ofrecidos en el sitio cinekomuna.com o, en su caso, por terceros a trav&eacute;s del SITIO WEB pueden estar sujetos a la contrataci&oacute;n previa del contenido, producto o servicio, en cuyo caso se especificar&aacute; de forma clara y se pondr&aacute; a disposici&oacute;n del USUARIO las condiciones generales o particulares por las que se rija el acceso a dichos contenidos.</p>"+
"<p>En caso de ser ofrecidos, a trav&eacute;s del SITIO WEB la utilizaci&oacute;n, prestaci&oacute;n y/o contrataci&oacute;n de productos o servicios, el hecho de ser utilizados y/o solicitados por el USUARIO implicar&aacute;, asimismo, la aceptaci&oacute;n sin reservas de las condiciones particulares que, en su caso, hayan sido establecidas al efecto, y que formar&aacute;n parte integrante del presente Aviso Legal.</p>"+
"<p>La utilizaci&oacute;n, prestaci&oacute;n y/o contrataci&oacute;n de los productos o servicios que, en su caso, puedan ser ofrecidos por el SITIO WEB puede estar sujeta a la previa observancia de requisitos formales tales como el registro previo, la cumplimentaci&oacute;n de formularios, formalizar la suscripci&oacute;n a los mismos, el abono de tarifas o tasas y/o la previa aceptaci&oacute;n de las condiciones particulares que resulten de aplicaci&oacute;n a los mismos.</p>"+
"<p>El TITULAR se reserva la facultad de dar por terminado, modificar, suspender o interrumpir, temporalmente o de forma indefinida, en cualquier momento y sin necesidad de preaviso, el acceso a los productos, servicios y/o contenidos del SITIO WEB, as&iacute; como la configuraci&oacute;n misma del SITIO WEB, prestaciones, productos, servicios y contenidos, sin posibilidad por parte del Usuario de reclamar ni exigir indemnizaci&oacute;n alguna; en particular, con motivo de operaciones de mantenimiento, reparaci&oacute;n, actualizaci&oacute;n, mejora y/o adecuaci&oacute;n a cambios t&eacute;cnicos, operativos y/o legales. Tras dicha terminaci&oacute;n, seguir&aacute;n vigentes las prohibiciones, restricciones y limitaciones contenidas en el presente Aviso Legal y/o en cualesquiera condiciones particulares que sean de aplicaci&oacute;n.</p>"+
"<p>&nbsp;</p>"+
"<p><strong>II. DEL USUARIO.</strong> <br />El acceso o utilizaci&oacute;n del SITIO WEB, as&iacute; como de los recursos habilitados para interactuar entre los USUARIOS, o entre el USUARIO y el TITULAR tales como medios para realizar publicaciones o comentarios, confiere la condici&oacute;n de USUARIO del SITIO WEB, por lo que quedar&aacute; sujeto a los presentes T&Eacute;RMINOS Y CONDICIONES, as&iacute; como a sus ulteriores modificaciones, sin perjuicio de la aplicaci&oacute;n de la legislaci&oacute;n aplicable, por tanto, se tendr&aacute;n por aceptados desde el momento en el que se accede al SITIO WEB. Dada la relevancia de lo anterior, se recomienda al USUARIO revisar las actualizaciones que se pudieran realizar a los presentes T&Eacute;RMINOS Y CONDICIONES.</p>"+
"<p>Es responsabilidad del USUARIO utilizar el SITIO WEB de acuerdo a Ia forma en Ia que fue dise&ntilde;ado; en este sentido, queda prohibida la utilizaci&oacute;n de cualquier tipo de software que automatice la interacci&oacute;n o descarga de los contenidos o servicios proporcionados a trav&eacute;s del SITIO WEB. Adem&aacute;s, el USUARIO se compromete a utilizar la informaci&oacute;n, contenidos o servicios ofrecidos a trav&eacute;s del SITIO WEB de manera l&iacute;cita, sin contravenir lo dispuesto en los presentes T&Eacute;RMINOS Y CONDICIONES, la moral o el orden p&uacute;blico, y se abstendr&aacute; de realizar cualquier acto que pueda suponer una afectaci&oacute;n a los derechos de terceros, o perjudique de alg&uacute;n modo el funcionamiento del SITIO WEB as&iacute; como la integridad de los dem&aacute;s usuarios.</p>"+
"<p>Asimismo, el usuario se compromete a proporcionar informaci&oacute;n l&iacute;cita y veraz en los formularios habilitados en el SITIO WEB, en los cuales el usuario tenga que proporcionar ciertos datos o informaci&oacute;n para el acceso a alg&uacute;n contenido, producto o servicio ofrecido por el propio SITIO WEB. En todo caso, el USUARIO notificar&aacute; de forma inmediata al TITULAR acerca de cualquier hecho que permita suponer el use indebido de Ia informaci&oacute;n registrada en dichos formularios, tales como, robo, extrav&iacute;o, o acceso no autorizado a cuentas y/o contrase&ntilde;as, con el fin de proceder a su inmediata cancelaci&oacute;n.</p>"+
"<p>En particular, el USUARIO se compromete a no trasmitir, introducir, difundir y poner a disposici&oacute;n de terceros y/o otros USUARIOS, cualquier tipo de material e informaci&oacute;n (datos contenidos, mensajes, dibujos, archivos de sonido e imagen, fotograf&iacute;as, software, etc.) que sean contrarios a la ley, la moral, y el orden p&uacute;blico. A t&iacute;tulo enunciativo, y en ning&uacute;n caso limitativo o excluyente, el USUARIO se compromete a cumplir las siguientes 'Prohibiciones y Restricciones' actualizadas peri&oacute;dicamente por el TITULAR. En consecuencia no deber&aacute;:</p>"+
"<ul>"+
"<li>Almacenar, transmitir o facilitar de alg&uacute;n otro modo, a trav&eacute;s del SITIO WEB o en conexi&oacute;n con el mismo:</li>"+
"<li>Nada que sea o se pueda considerar (a) amenazador, acosador, degradante, odioso o intimidatorio; (b) difamatorio; (c) fraudulento o il&iacute;cito; (d) obsceno, indecente, pornogr&aacute;fico o de cualquier otro modo, ofensivo; o (e) publicidad il&iacute;cita, enga&ntilde;osa o desleal."+
"<ul>"+
"<li>CineKomuna se reserva el derecho de retirar todos aquellos comentarios y aportaciones que vulneren la ley, el respeto a Ia dignidad de la persona, que sean discriminatorios, atenten contra los derechos de tercero o el orden p&uacute;blico, o bien, que a su juicio no resulten adecuados para su publicaci&oacute;n.</li>"+
"<li>En cualquier caso, CineKomuna no ser&aacute; responsable de las opiniones vertidas por los usuarios a trav&eacute;s de comentarios o publicaciones que estos realicen.</li>"+
"</ul>"+
"</li>"+
"<li>Material que est&eacute; protegido por derechos de propiedad intelectual y autor, marca comercial, secreto comercial, derecho de publicidad o cualquier otro derecho relativo al patrimonio, sin el previo consentimiento expreso del titular de dichos derechos.</li>"+
"<li>A su discreci&oacute;n, El TITULAR se reserva el derecho de verificar y monitorear de manera rutinaria todo el contenido proporcionado y expuesto en los perfiles por los USUARIOS. De igual manera, puede solicitar en cualquier momento al USUARIO que proporcione evidencia de que est&aacute; cumpliendo con los requisitos de titularidad de derechos.<br />"+
"<ul>"+
"<li>Evidencia de su propiedad y / o derechos de propiedad intelectual que subsisten en relaci&oacute;n con el contenido.</li>"+
"<li>Evidencia de sus derechos para usar cualquier dato personal o informaci&oacute;n relacionada con terceros; y detalles de los licenciantes, licencias y aprobaciones relevantes.</li>"+
"<li>Los detalles necesarios para poder acreditar correctamente al autor / creador/ titular legal de cualquier imagen, sonido, video u otro contenido.</li>"+
"</ul>"+
"</li>"+
"<li>A su discreci&oacute;n, El TITULAR se reserva el derecho de modificar cualquier contenido que determine falso y/o enga&ntilde;oso dentro del perfil o perfiles de un USUARIO con la finalidad de garantizar el correcto funcionamiento del SITIO WEB siempre respetando la titularidad sobre la propiedad intelectual del USUARIO.</li>"+
"<li>El USUARIO libera al TITULAR de cualquier responsabilidad legal, jur&iacute;dica y/o penal que implique transgredir el derecho de autor y/o la propiedad intelectual de cualquier tercero que afirme que cualquier contenido publicado o cargado por el dicho USUARIO en el SITIO WEB constituye una violaci&oacute;n de sus derechos de propiedad intelectual o de su derecho a la privacidad.</li>"+
"<li>Material que pueda dar lugar a responsabilidad penal o civil; que fomente conductas que constituyen delito o que favorezca o proporcione informaci&oacute;n e instrucciones para realizar actividades ilegales.</li>"+
"<li>Un virus u otro c&oacute;digo inform&aacute;tico, archivo o programa que sea perjudicial o invasivo o que pueda o est&eacute; previsto para da&ntilde;ar o piratear el funcionamiento o controlar la utilizaci&oacute;n tanto de hardware como de software o equipos.</li>"+
"<li>Material de informaci&oacute;n no p&uacute;blica sobre una sociedad sin la debida autorizaci&oacute;n al respecto.</li>"+
"<li>Utilizar el SITIO WEB para cualquier fin fraudulento o ilegal.</li>"+
"<li>Utilizar el SITIO WEB para difamar, enga&ntilde;ar, acusar, acechar, amenazar o violar de alguna otra forma los derechos legales de terceros y/o otros USUARIOS, inclusive, sin que esto suponga limitaci&oacute;n, derechos de privacidad o de publicidad de terceros, o recopilar o recoger informaci&oacute;n personalmente identificable de otros USUARIOS de la P&aacute;gina web.</li>"+
"<li>Hacerse pasar por otra persona o entidad, inclusive cualquiera de nuestros representantes (o nuestros afiliados); declarar con falsedad o tergiversar de alguna otra forma su afiliaci&oacute;n con alguna persona o entidad; o expresar o insinuar que el TITULAR respalda cualquier declaraci&oacute;n o registro que haga el Usuario.</li>"+
"<li>Interferir o interrumpir el funcionamiento del SITIO WEB o de los servidores o redes utilizados para que el SITIO WEB se encuentre disponible; o contravenir requisitos, procedimientos, pol&iacute;ticas o reglamentos de dichas redes.</li>"+
"<li>Restringir o impedir el uso del SITIO WEB a cualquier otra persona.</li>"+
"<li>Reproducir, duplicar, copiar, vender, revender o explotar de alguna otra forma para fines comerciales parte del SITIO WEB, su utilizaci&oacute;n o acceso al mismo as&iacute; como sus &ldquo;Innovaciones&rdquo;"+
"<ul>"+
"<li>Entendiendose como 'Innovaciones' colectivamente todas y cada una de las ideas, conceptos, inventos, descubrimientos, desarrollos, software, contenido, obras textuales o artísticas, video, gráficos, grabaciones de sonido, conocimientos técnicos, estructuras, diseños, fórmulas, algoritmos, métodos, productos, procesos, sistemas y tecnologías en cualquier etapa de desarrollo que sean concebidos, creados, desarrollados o reducidos a la práctica por el TITULAR individualmente o con la ayuda de terceros; todas y cada una de las patentes, patentes pendientes, derechos de autor, derechos morales, trabajos protegidos por derechos de autor, marcas comerciales y cualquier otro derecho de propiedad intelectual en ellos; y todas y cada una de las mejoras, modificaciones, trabajos derivados de, otros derechos y reclamos relacionados con cualquiera de los anteriores bajo las leyes de cualquier jurisdicción ya existentes o en adelante concebidas.</li>"+
"</ul>"+
"</li>"+
"</ul>"+
"<p>Mensajes internos e interacci&oacute;n con dem&aacute;s USUARIOS: Dentro del ecosistema propio de Cinekomuna, el SITIO WEB facilita la mensajer&iacute;a y el intercambio de informaci&oacute;n de muchas maneras, que incluyen, entre otros pero no limitados a, visitas de USUARIOS a los distintos perfiles, mensajes internos de USUARIO a USUARIO dentro del SITIO WEB y el uso de redes sociales y datos de contacto externos proporcionadas por el mismo USUARIO. Es decisi&oacute;n personal de cada USUARIO poner la informaci&oacute;n de contacto que deseen sea visible para los dem&aacute;s USUARIOS. En NING&Uacute;N momento el TITULAR y/o el SITIO WEB le proporciona a otro USUARIO as&iacute; como a terceros el correo electr&oacute;nico personal que uso el USUARIO en su registro inicial. El USUARIO en particular, acepta no enviar spam ni irritar ni acosar a otros usuarios</p>"+
"<p>Recomendaciones: Es posible que de vez en cuando el SITIO WEB haga sugerencias y/o recomendaciones con respecto al correcto funcionamiento del SITIO WEB as&iacute; como informaci&oacute;n relevante a otros USUARIOS, perfiles y/o proyectos que puedan ser de inter&eacute;s o relevancia para el USUARIO y contribuyan a una experiencia m&aacute;s completa del SITIO WEB. El USUARIO no tiene la obligaci&oacute;n de contactar o ver estas recomendaciones de user experience as&iacute; como de otros USUARIOS y/o proyectos.</p>"+
"<p>Comunicaciones electr&oacute;nicas; El USUARIO est&aacute; consciente que usar cualquier servicio del SITIO WEB as&iacute; como cualquier comunicaci&oacute;n v&iacute;a correo se hace de manera digital y/o electr&oacute;nica. El USUARIO da su consentimiento para recibir nuestras comunicaciones electr&oacute;nicamente. EL USUARIO acepta que todos los acuerdos, avisos, divulgaciones y otras comunicaciones que le sean proporcionadas por el TITULAR de manera digital satisfacen cualquier requisito legal de que dichas comunicaciones se realicen por escrito.</p>"+
"<p>Todas las marcas, nombres comerciales, signos distintivos de cualquier naturaleza que aparezcan en el Sitio son de propiedad de sus respectivos propietarios, sin que pueda entenderse que el uso o acceso al Sitio y/o Servicios atribuya al USUARIO derecho alguno sobre dichas marcas, nombres comerciales y/o signos distintivos.</p>"+
"<p>El TITULAR no asumir&aacute; ninguna responsabilidad derivada del uso por terceros del contenido del Sitio y podr&aacute; ejercitar todas las acciones civiles o penales que le correspondan en caso de infracci&oacute;n de estos derechos por parte de alg&uacute;n Usuario.</p>"+
"<p>El incumplimiento por parte del USUARIO de la normativa vigente de estos t&eacute;rminos y condiciones facultar&aacute; a el TITULAR a restringir el acceso al SITIO WEB y/o a deshabilitar la cuenta de USUARIO sin perjuicio de las acciones legales que se estimen oportunas. El USUARIO reconoce y acepta que si el TITULAR inhabilita el acceso a su cuenta, podr&aacute; dejar de tener acceso a los Servicios, la informaci&oacute;n de su cuenta o cualesquiera archivos u otros contenidos almacenados en su cuenta.</p>"+
"<p>El solo acceso al SITIO WEB no supone el establecimiento de ning&uacute;n tipo de relaci&oacute;n entre el TITULAR y el USUARIO.</p>"+
"<p>En todo caso, el acceso, navegaci&oacute;n y uso del Website y App y, en su caso, el uso o contrataci&oacute;n de los productos o servicios que sean ofrecidos a trav&eacute;s del mismo se hace bajo la &uacute;nica y exclusiva responsabilidad del USUARIO, por lo que &eacute;ste se compromete a observar diligente y fielmente cualquier instrucci&oacute;n adicional, impartida por el SITIO WEB o por personal autorizado del SITIO WEB, relativa al uso del SITIO WEB y sus contenidos.</p>"+
"<p>El TITULAR tendr&aacute;, en todo momento, el derecho de negar, restringir, suspender, cancelar o condicionar al USUARIO el acceso al y/o uso del el SITIO WEB, ya sea total o parcialmente, de manera temporal o definitiva y sin necesidad de previo aviso, si el Usuario quebranta cualquiera de las estipulaciones de los presentes T&eacute;rminos y Condiciones, si comete cualquier acto contrario a las leyes aplicables vigentes, si no pudiera verificarse su identidad, si cualquier informaci&oacute;n proporcionada por el mismo fuere falsa o por cualquier otra causa, a entera discreci&oacute;n de y sin responsabilidad para el TITULAR. <br /> <br /><strong>III. MEMBRESIAS PREMIUM</strong> <br />Adem&aacute;s de ofrecer una membres&iacute;a b&aacute;sica (gratuita) a todos sus USUARIOS, el SITIO WEB ofrece la posibilidad de escalar a una membres&iacute;a premium. La membres&iacute;a premium permite tener una experiencia de USUARIO m&aacute;s robusta y completa y cuenta con m&uacute;ltiples beneficios que se encuentran desglosados en la siguiente p&aacute;gina __________. Una vez contratada la membres&iacute;a premium, el USUARIO reconoce y acepta que las caracter&iacute;sticas y los precios pueden cambiar de vez en cuando. El SITIO WEB puede agregar caracter&iacute;sticas adicionales de vez en cuando o puede eliminar caracter&iacute;sticas y / o reemplazarlas con caracter&iacute;sticas similares o comparables. Cualquier cambio en los precios entrar&aacute; en vigencia al final del per&iacute;odo de suscripci&oacute;n correspondiente y con el conocimiento pleno del USUARIO que tal cambio se llevar&aacute; a cabo. Ser&aacute; responsabilidad en todo momento del TITULAR, mandar la comunicaci&oacute;n correspondiente por la v&iacute;a que considere oportuna al USUARIO informando dichos cambios. En todo caso, la utilizaci&oacute;n de datos financieros o patrimoniales para hacer un cargo o cobro, requerir&aacute;n de autorizaci&oacute;n expresa del USUARIO en todo momento. La compra puede estar sujeta a comisiones adicionales o a diferencias de precios en funci&oacute;n de su ubicaci&oacute;n (por ejemplo, tipos de cambio).</p>"+
"<ul>"+
"<li>Cancelacion y reembolso de membresia premium -"+
"<ul>"+
"<li>Sujeto a lo siguiente, los USUARIOS que compren una suscripci&oacute;n a una membres&iacute;a premium no podr&aacute;n cancelar la suscripci&oacute;n hasta el final del per&iacute;odo de suscripci&oacute;n seleccionado en el momento de la compra, o cualquier per&iacute;odo de renovaci&oacute;n. Todas las compras son definitivas y todas las tarifas pagadas incluyendo los impuestos correspondientes no son reembolsables, incluso si el SITIO WEB cancela una cuenta por incumplimiento de estos T&eacute;rminos y condiciones.</li>"+
"<li>El no utilizar cualquier suscripci&oacute;n o funci&oacute;n no dar&aacute; derecho al titular de la cuenta a ning&uacute;n reembolso.</li>"+
"</ul>"+
"</li>"+
"<li>Renovacion de membresia premium -<br />"+
"<ul>"+
"<li>Al final de cada per&iacute;odo de suscripci&oacute;n (y per&iacute;odos de renovaci&oacute;n subsiguientes), las suscripciones se renovar&aacute;n autom&aacute;ticamente por uno o m&aacute;s per&iacute;odos de renovaci&oacute;n. El per&iacute;odo de renovaci&oacute;n tendr&aacute; la misma duraci&oacute;n que el per&iacute;odo de suscripci&oacute;n original.</li>"+
"<li>En el caso de que no desee renovar el per&iacute;odo de suscripci&oacute;n, el USUARIO debe notificar al SITIO WEB antes de que comience el per&iacute;odo de renovaci&oacute;n de la suscripci&oacute;n.</li>"+
"<li>El TITULAR se reserva el derecho a negarse a renovar cualquier suscripci&oacute;n de un USUARIO por cualquier motivo.</li>"+
"</ul>"+
"</li>"+
"<li>Fin de suscripci&oacute;n de membres&iacute;a premium -<br />"+
"<ul>"+
"<li>Al final de cualquier suscripci&oacute;n premium, la cuenta se convierte autom&aacute;ticamente en una cuenta b&aacute;sica (gratuita). Es posible que se deshabilite cualquier servicio adicional previamente accesible como parte de la suscripci&oacute;n premium. Esto puede evitar que el titular de la cuenta acceda o use cierto Contenido</li>"+
"</ul>"+
"</li>"+
"</ul>"+
"<p><strong>IV. DEL ACCESO Y NAVEGACI&Oacute;N EN EL SITIO WEB.</strong> <br />El TITULAR no garantiza de ning&uacute;n modo la continuidad y disponibilidad de los contenidos, productos o servicios ofrecidos a trav&eacute;s del SITIO WEB, no obstante, el TITULAR llevar&aacute; a cabo las acciones que de acuerdo a sus posibilidades le permitan mantener el buen funcionamiento del SITIO WEB, sin que esto suponga alguna responsabilidad de parte de <br />Cinekomuna.</p>"+
"<p>De igual forma Cinekomuna no ser&aacute; responsable ni garantiza que el contenido o software al que pueda accederse a trav&eacute;s del SITIO WEB, se encuentre libre de errores, software malicioso, o que pueda causar alg&uacute;n da&ntilde;o a nivel de software o hardware en el equipo a trav&eacute;s del cual el USUARIO accede al SITIO WEB.</p>"+
"<br/>"+
"<p><strong>V. POL&Iacute;TICA DE PRIVACIDAD Y PROTECCI&Oacute;N DE DATOS.</strong> <br />Cuando sea necesario que el Usuario se registre o facilite datos personales, ser&aacute; advertido convenientemente, de dicha necesidad.</p>"+
"<p>En todo caso, la recogida y el tratamiento de los datos personales se llevar&aacute; a cabo con sujeci&oacute;n a los principios y obligaciones de la normativa aplicable en materia de protecci&oacute;n de datos, y de conformidad con lo previsto en la pol&iacute;tica de privacidad que puede ser consultada en el siguiente enlace @________, la cual forma parte integrante de este Aviso Legal.</p>"+
"<p>De conformidad con lo establecido en la Ley Federal de Protecci&oacute;n de Datos Personales en Posesi&oacute;n de Particulares, el TITULAR se compromete a adoptar las medidas necesarias que est&eacute;n a su alcance para asegurar la privacidad de los datos personales recabados de forma que se garantice su seguridad, se evite su alteraci&oacute;n, p&eacute;rdida o tratamiento no autorizado.</p>"+
"<p>Adem&aacute;s, a efecto de dar cumplimiento a lo establecido en la Ley Federal de Protecci&oacute;n de Datos Personales en Posesi&oacute;n de Particulares, todo dato personal que sea recabado a trav&eacute;s del SITIO WEB, ser&aacute; tratado de conformidad con los principios de licitud, calidad, finalidad, lealtad, y responsabilidad. Todo tratamiento de datos personales quedar&aacute; sujeto al consentimiento de su titular. En todo caso, la utilizaci&oacute;n de datos financieros o patrimoniales, requerir&aacute;n de autorizaci&oacute;n expresa de sus titulares, no obstante, esta podr&iacute;a darse a trav&eacute;s del propio SITIO WEB utilizando los mecanismos habilitados para tal efecto, y en todo caso se dar&aacute; la mayor diligencia y cuidado a este tipo de datos. Lo mismo ocurrir&aacute; en el caso de datos personales sensibles, considerando por estos aquellos que debido a una utilizaci&oacute;n indebida puedan dar origen a discriminacion o su divulgaci&oacute;n conlleve un riesgo para el titular.</p>"+
"<p>En todo momento se procurar&aacute; que los datos personales contenidos en las bases de datos o archivos que en su caso se utilicen, sean pertinentes, correctos y actualizados para los fines para los cuales fueron recabados.</p>"+
"<p>El SITIO WEB podr&aacute; incluir hiperv&iacute;nculos o enlaces que permitan acceder a p&aacute;ginas web de terceros distintos de Cinekomuna. Los titulares de dichos sitios web dispondr&aacute;n de sus propias pol&iacute;ticas de privacidad y protecci&oacute;n de datos, por lo cual Cinekomuna no asume ning&uacute;n tipo de responsabilidad por los datos que sean facilitados por el USUARIO a trav&eacute;s de cualquier sitio web distinto a cinekomuna.com.</p>"+
"<p>CineKomuna se reserva el derecho a modificar su Pol&iacute;tica de Privacidad, de acuerdo a sus necesidades o derivado de alg&uacute;n cambio en Ia legislaci&oacute;n. El acceso o utilizaci&oacute;n del SITIO WEB despu&eacute;s de dichos cambios, implica la aceptaci&oacute;n de estos cambios.</p>"+
"<p>Por otra parte, el acceso al SITIO WEB puede implicar la utilizaci&oacute;n de cookies, las cuales, son peque&ntilde;as cantidades de informaci&oacute;n que se almacenan en el navegador utilizado por el USUARIO. Las cookies facilitan la navegaci&oacute;n, la hacen m&aacute;s amigable, y no da&ntilde;an el dispositivo de navegaci&oacute;n, para ello, pueden recabar informaci&oacute;n para ingresar al SITIO WEB, almacenar las preferencias del USUARIO, as&iacute; como la interacci&oacute;n que este tenga con el SITIO WEB, como por ejemplo pero no limitado a: Ia fecha y hora en Ia que se accede al SITIO WEB, el tiempo que se ha hecho use de este, los sitios visitados antes y despu&eacute;s del mismo, el n&uacute;mero de p&aacute;ginas visitadas, Ia direcci&oacute;n IP de la cual accede el usuario, la frecuencia de visitas, etc.</p>"+
"<p>Este tipo de informaci&oacute;n ser&aacute; utilizada para mejorar el SITIO WEB, detectar errores, y posibles necesidades que el USUARIO pueda tener, lo anterior a efecto de ofrecer a los USUARIOS servicios y contenidos de mejor calidad. En todo caso, Ia informaci&oacute;n que se recopile ser&aacute; an&oacute;nima y no se identificara a usuarios individuales.</p>"+
"<p>En caso de que el USUARIO no desee que se recopile este tipo de informaci&oacute;n deber&aacute; deshabilitar, rechazar, restringir y/o eliminar el uso de cookies en su navegador de internet. Los procedimientos para realizar estas acciones pueden diferir de un navegador a otro; en consecuencia, se sugiere revisar las instrucciones facilitadas por el desarrollador del navegador. En el supuesto de que rechace el uso de cookies (total o parcialmente) el USUARIO podr&aacute; continuar haciendo uso del SITIO WEB, aunque podr&iacute;an quedar deshabilitadas algunas de las funciones del mismo.</p>"+
"<p>El USUARIO puede consultar en todo momento nuestro aviso sobre la pol&iacute;ticas de &ldquo;cookies&rdquo; en el siguiente enlace ____________.</p>"+
"<p>Es posible que en el futuro estas pol&iacute;ticas respecto a las cookies cambien o se actualicen, por ello es recomendable revisar las actualizaciones que se realicen a los presentes T&Eacute;RMINOS Y CONDICIONES, con objetivo de estar adecuadamente informado sobre c&oacute;mo y para qu&eacute; utilizamos las cookies que se generan al ingresar o hacer uso del SITIO WEB.</p>"+
"<br/>"+
"<p><strong>VI. POLITICA DE ENLACES.</strong> <br />El SITIO WEB puede contener enlaces, contenidos, servicios o funciones, de otros sitios de Internet pertenecientes y/o gestionados por terceros y/o otros USUARIOS, como por ejemplo pero no limitado a im&aacute;genes, videos, audios, comentarios, motores de b&uacute;squeda, etc.</p>"+
"<p>La utilizaci&oacute;n de estos enlaces, contenidos, servicios o funciones, tiene por objeto mejorar la experiencia del USUARIO al hacer uso del SITIO WEB, sin que pueda considerarse una sugerencia, recomendaci&oacute;n o invitaci&oacute;n para hacer uso de sitios externos. CineKomuna en ning&uacute;n caso revisara o controlara el contenido de los sitios externos, de igual forma, no hace propios los productos, servicios, contenidos, y cualquier otro material existente en los referidos sitios enlazados; por lo cual, tampoco se garantizar&aacute; la disponibilidad, exactitud, veracidad, validez o legalidad de los sitios externos a los que se pueda tener acceso a trav&eacute;s del SITIO WEB. As&iacute; mismo, el TITULAR no asume ninguna responsabilidad por los da&ntilde;os y perjuicios que pudieran producirse por el acceso o uso, de los contenidos, productos o servicios disponibles en los sitios web no gestionados por CineKomuna a los que se pueda acceder mediante el SITIO WEB.</p>"+
"<br/>"+
"<p><strong>VII. POL&Iacute;TICA EN MATERIA DE PROPIEDAD INTELECTUAL E INDUSTRIAL.</strong> <br />Cinekomuna por s&iacute; o como parte cesionaria, es titular de todos los derechos de propiedad intelectual e industrial del SITIO WEB, entendiendo por &eacute;ste el c&oacute;digo fuente que hace posible su funcionamiento as&Iacute; como las im&aacute;genes, archivos de audio o video, logotipos, marcas, combinaciones de colores, estructuras, dise&ntilde;os, algoritmos propios del SITIO WEB y dem&aacute;s elementos que lo distinguen. Ser&aacute;n, por consiguiente, protegidas por la legislaci&oacute;n mexicana en materia de propiedad intelectual e industrial, as&iacute; como por los tratados internacionales aplicables. Por consiguiente, queda expresamente prohibida la copia, reproducci&oacute;n, distribuci&oacute;n, o difusi&oacute;n de los contenidos del SITIO WEB, con fines comerciales, en cualquier soporte y por cualquier medio, sin la autorizaci&oacute;n de Cinekomuna.</p>"+
"<p>El TITULAR es due&ntilde;o de todos los derechos de copia, marcas, derechos de propiedad intelectual, know-how o cualesquiera otros derechos relacionados con el Servicio o con el Software necesario para la prestaci&oacute;n del Servicio. El USUARIO no adquiere derecho ni licencia alguna, cualquiera que sea su naturaleza, salvo la propia prestaci&oacute;n del servicio.<br /> <br />El USUARIO se compromete a respetar los derechos de propiedad intelectual e industrial del TITULAR. No obstante, adem&aacute;s de poder visualizar los elementos del SITIO WEB podr&aacute; imprimirlos, copiarlos o almacenarlos, siempre y cuando sea exclusivamente para su uso estrictamente personal.</p>"+
"<p>Por otro lado, el USUARIO, se abstendr&aacute; de suprimir, alterar, o manipular cualquier elemento, archivo, o contenido, del SITIO WEB, y por ning&uacute;n motivo realizara actos tendientes a vulnerar la seguridad, los archivos o bases de datos que se encuentren protegidos, ya sea a trav&eacute;s de un acceso restringido mediante un usuario y contrase&ntilde;a, o porque no cuente con los permisos para visualizarlos, editarlos o manipularlos.</p>"+
"<p>En caso de que el USUARIO o alg&uacute;n tercero consideren que cualquiera de los contenidos del SITIO WEB suponga una violacion de los derechos de protecci&oacute;n de la propiedad industrial o intelectual, deber&aacute; comunicarlo inmediatamente a CineKomuna a trav&eacute;s de los datos de contacto disponibles en el propio SITIO WEB.</p>"+
"<p>Contenido de USUARIOS; el USUARIO reconoce y acepta que es el titular legal del contenido expuesto en sus perfiles (personal, empresa, proyectos) y/o seg&uacute;n sea el caso, que ha conseguido el consentimiento expreso del titular de dicho contenido que est&eacute; protegido por derechos de propiedad intelectual, marca comercial, secreto comercial, derecho de publicidad o cualquier otro derecho relativo al patrimonio para su publicaci&oacute;n en el respectivo perfil.</p>"+
"<p>El USUARIO acepta que el SITIO WEB podr&aacute; utilizar el contenido que proporciona y, cuando sea relevante, las marcas comerciales relacionadas con su empresa y/o proyecto (producciones/ portafolios), con el fin de operar y mantener el Sitio y los Servicios. El USUARIO reconoce que su contenido puede publicarse y ponerse a disposici&oacute;n de otros usuarios as&iacute; como del p&uacute;blico general de nuestros sitios, servicios y redes sociales con un fin de promoci&oacute;n del SITIO WEB. Esto se har&aacute; con el consentimiento previo del USUARIO en cuesti&oacute;n. El USUARIO mantendr&aacute; en todo momento su titularidad sobre la propiedad intelectual.</p>"+
"<br/>"+
"<p><strong>VIII. R&Eacute;GIMEN GENERAL DE EXCLUSI&Oacute;N DE GARANT&Iacute;A Y DE RESPONSABILIDAD</strong><br />El Administrador realizar&aacute; todos los esfuerzos que sean razonables para intentar garantizar la disponibilidad y accesibilidad al SITIO WEB veinticuatro horas al d&iacute;a durante el a&ntilde;o en curso.</p>"+
"<p>No obstante, en ocasiones, y, por ejemplo, debido a causas de fuerza mayor en la infraestructura del Administrador y/o la actualizaci&oacute;n de operaciones de mantenimiento necesarias que, en general, impliquen la suspensi&oacute;n del acceso o utilizaci&oacute;n del Sitio, podr&aacute;n producirse interrupciones por el tiempo que resulte necesario acometer dichas tareas. Por lo tanto, el Administrador no se hace responsable por posibles da&ntilde;os y perjuicios que el Usuario pueda tener debido a la falta de disponibilidad y accesibilidad del Sitio y de los servicios en dichos periodos de interrupci&oacute;n.</p>"+
"<p>El Administrador no se responsabiliza de los eventuales errores tipogr&aacute;ficos, formales o num&eacute;ricos que pueda contener el Sitio, ni de la exactitud de la informaci&oacute;n contenida en &eacute;l.</p>"+
"<p>El SITIO WEB puede contener informaci&oacute;n, opiniones, consejos, advertencias y declaraciones proporcionadas por diferentes fuentes de informaci&oacute;n, as&iacute; como por cualquier USUARIO del SITIO WEB. El TITULAR no se hace responsable de las decisiones de los USUARIOS basadas en la informaci&oacute;n proporcionada a trav&eacute;s del SITIO WEB. Cualquier informaci&oacute;n publicada en el SITIO WEB debe entenderse hecha exclusivamente para fines generales. El TITULAR no garantiza ni respalda la exactitud o fiabilidad de cualquier informaci&oacute;n o contenido. En consecuencia, el TITULAR no garantiza la fiabilidad, utilidad o veracidad de la informaci&oacute;n, ni tampoco la continuidad, precisi&oacute;n o exhaustividad de dicha informaci&oacute;n ni de los resultados obtenidos a partir del uso que se pueda dar a dicha informaci&oacute;n y no tendr&aacute; ninguna responsabilidad respecto de los USUARIOS.</p>"+
"<p>El TITULAR no se hace responsable y, en la m&aacute;xima medida permitida por la legislaci&oacute;n aplicable, excluye cualesquiera garant&iacute;as, expresas o impl&iacute;citas, relativas a la mercantilidad, idoneidad para un fin concreto, no cumplimiento, exactitud, fiabilidad, integridad o actualidad de los contenidos, servicios, productos u otros elementos incluidos en el SITIO WEB, o los resultados obtenidos de acceder y usar el SITIO WEB y/o el contenido del mismo. El SITIO WEB y cualquier contenido, producto y/o servicio ofrecido dentro del mismo son ofrecidos &ldquo;tal cual&rdquo;. El USUARIO es consciente y acepta voluntariamente que el uso de la informaci&oacute;n publicada y/o suministrada con relaci&oacute;n a los productos o servicios del SITIO WEB tiene lugar bajo su &uacute;nica y exclusiva responsabilidad.</p>"+
"<p>En particular, en la m&aacute;xima medida permitida por la legislaci&oacute;n aplicable, el TITULAR no garantiza ni se hace responsable de:</p>"+
"<ul>"+
"<li>La continuidad de los contenidos del SITIO WEB y/o la falta de disponibilidad o accesibilidad del SITIO WEB o continuidad t&eacute;cnica del mismo;</li>"+
"<li>La existencia de interrupciones o errores en el acceso al SITIO WEB, as&iacute; como problemas t&eacute;cnicos o fallos que se produzcan durante la conexi&oacute;n a Internet;</li>"+
"<li>La ausencia de errores o inexactitudes en los contenidos, servicios o productos;</li>"+
"<li>La ausencia de virus y dem&aacute;s componentes da&ntilde;inos en el SITIO WEB o en el servidor que lo suministra;</li>"+
"<li>La invulnerabilidad del SITIO WEB y/o la inexpugnabilidad de las medidas de seguridad que se adopten en el mismo;</li>"+
"<li>La fiabilidad y/o adecuaci&oacute;n, para un prop&oacute;sito o fin particular, del SITIO WEB, de los productos o servicios incorporados en el mismo, y de la informaci&oacute;n publicada y/o suministrada con relaci&oacute;n a dichos productos o servicios;</li>"+
"<li>En su caso, la falta de utilidad, beneficio o rendimiento de los contenidos o servicios del SITIO WEB.</li>"+
"<li>Los da&ntilde;os o perjuicios que cause, a s&iacute; mismo o a un tercero, cualquier persona que infringiera las condiciones, normas e instrucciones que el TITULAR establece en el SITIO WEB o a trav&eacute;s de la vulneraci&oacute;n de los sistemas de seguridad del mismo;</li>"+
"<li>Cualesquiera otros da&ntilde;os que pudieran ser causados por motivos inherentes al no funcionamiento o al funcionamiento defectuoso del SITIO WEB o de los sitios web a los que, en su caso, se hayan podido establecer enlaces (links).</li>"+
"</ul>"+
"<p>El TITULAR realiza los m&aacute;ximos esfuerzos para evitar errores y fallas en los contenidos que se publican en el SITIO WEB. Todos los contenidos que se ofrecen a trav&eacute;s del SITIO WEB se encuentran actualizados, reserv&aacute;ndose el TITULAR la facultad de poder modificarlos en cualquier momento. El TITULAR no se responsabiliza de las consecuencias que puedan derivarse de los errores en los contenidos, que puedan aparecer en el SITIO WEB, cuando sean proporcionados por terceros y el TITULAR no haya tenido conocimiento de dichos errores.</p>"+
"<p>En la m&aacute;xima medida permitida por la legislaci&oacute;n aplicable, el TITULAR no ser&aacute; responsable por la p&eacute;rdida de beneficios, ingresos, datos, p&eacute;rdidas financieras ni por da&ntilde;os indirectos, especiales, derivados, ejemplares o punitivos. En todo caso, la responsabilidad total del TITULAR por cualquier reclamaci&oacute;n realizada bajo estas condiciones, incluida por cualquier garant&iacute;a impl&iacute;cita, se limita al importe que el Usuario haya abonado por el uso de servicios del SITIO WEB. En ning&uacute;n caso, el TITULAR ser&aacute; responsable por cualquier p&eacute;rdida o da&ntilde;o que no sean previsibles de forma razonable.</p>"+
"<p>El USUARIO reconoce y acepta que El TITULAR y el SITIO WEB solo facilita el canal de conexi&oacute;n entre los perfiles registrados. El TITULAR no se hace responsable de las comunicaciones abiertas y privadas entre los distintos USUARIOS del SITIO WEB, ya sean v&iacute;a mensaje, chat, email o por convocatorias a empleos y castings. El TITULAR tampoco se hace responsable de las relaciones creativas y/o laborales que se hagan entre los USUARIOS del SITIO WEB as&iacute; como sus respectivas consecuencias negativas y/o positivas. Si el USUARIO tiene alguna sospecha sobre la credibilidad de alg&uacute;n otro USUARIO, la comunicaci&oacute;n que ha tenido con otro USUARIO y/o la veracidad de un perfil (personal, empresa, proyecto) puede denunciarlo o ponerse en contacto con el TITULAR para intentar validar su veracidad.</p>"+
"<br/>"+
"<p><strong>IX. LEGISLACI&Oacute;N Y JURISDICCI&Oacute;N APLICABLE.</strong> <br />CineKomuna se reserva la facultad de presentar las acciones civiles o penales que considere necesarias por la utilizaci&oacute;n indebida del SITIO WEB, sus contenidos, productos o servicios, o por el incumplimiento de los presentes T&Eacute;RMINOS Y CONDICIONES.</p>"+
"<p>La relaci&oacute;n entre el USUARIO y CineKomuna se regir&aacute; por la legislaci&oacute;n vigente en Mexico, especificamente en la Ciudad de M&eacute;xico. De surgir cualquier controversia en relaci&oacute;n a la interpretaci&oacute;n y/o a la aplicaci&oacute;n de los presentes T&Eacute;RMINOS Y CONDICIONES, las partes se someter&aacute;n a la jurisdicci&oacute;n ordinaria de los tribunales que correspondan conforme a derecho en el estado al que se hace referencia.</p>"+
"<p><strong>Fecha &uacute;ltima de actualizaci&oacute;n: 1 de Septiembre de 2020.</strong></p>"
}